[package]
name    = "common-events"
version = "0.0.0"
authors = ["Mihai Eremin <mihai@xoxno.com>"]
edition = "2021"

[lib]
path = "src/events.rs"

[dependencies.common-structs]
path = "../structs"

[dependencies.multiversx-sc]
version = "0.57.0"
