// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           29
// Async Callback:                       1
// Total number of exported functions:  32

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lending_pool
    (
        init => init
        upgrade => upgrade
        supply => supply
        withdraw => withdraw
        borrow => borrow
        repay => repay
        liquidate => liquidate
        updatePositionInterest => update_collateral_with_interest
        updatePositionDebt => update_borrows_with_debt
        getLiqPoolTemplateAddress => liq_pool_template_address
        createLiquidityPool => create_liquidity_pool
        upgradeLiquidityPool => upgrade_liquidity_pool
        setAggregator => set_aggregator
        setAssetLoanToValue => set_asset_loan_to_value
        setAssetLiquidationBonus => set_asset_liquidation_bonus
        setAssetLiquidationThreshold => set_asset_liquidation_threshold
        getPoolAddress => get_pool_address
        registerAccountToken => register_account_token
        getAccountToken => account_token
        getAccountPositions => account_positions
        getDepositPositions => deposit_positions
        getBorrowPositions => borrow_positions
        getPoolAllowed => pools_allowed
        getAssetLoanToValue => asset_loan_to_value
        getAssetLiquidationThreshold => asset_liquidation_threshold
        getAssetLiquidationBonus => asset_liquidation_bonus
        getCollateralAmountForToken => get_collateral_amount_for_token
        getTotalCollateralAvailable => get_total_collateral_in_dollars
        getLiquidationCollateralAvailable => get_liquidation_collateral_available
        getLtvCollateralInDollars => get_ltv_collateral_in_dollars
        getTotalBorrowInDollars => get_total_borrow_in_dollars
    )
}

multiversx_sc_wasm_adapter::async_callback! { lending_pool }
