// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           44
// Async Callback:                       1
// Total number of exported functions:  47

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    lending_pool
    (
        init => init
        upgrade => upgrade
        supply => supply
        withdraw => withdraw
        borrow => borrow
        repay => repay
        liquidate => liquidate
        flashLoan => flash_loan
        updatePositionInterest => update_collateral_with_interest
        updatePositionDebt => update_borrows_with_debt
        getLiqPoolTemplateAddress => liq_pool_template_address
        createLiquidityPool => create_liquidity_pool
        upgradeLiquidityPool => upgrade_liquidity_pool
        setAggregator => set_aggregator
        addEModeCategory => add_e_mode_category
        editEModeCategory => edit_e_mode_category
        removeEModeCategory => remove_e_mode_category
        addAssetToEModeCategory => add_asset_to_e_mode_category
        editAssetInEModeCategory => edit_asset_in_e_mode_category
        removeAssetFromEModeCategory => remove_asset_from_e_mode_category
        editAssetConfig => edit_asset_config
        getPoolAddress => get_pool_address
        registerAccountToken => register_account_token
        registerStableToken => register_stable_token
        getAccountToken => account_token
        getAccountPositions => account_positions
        getStableToken => stable_token
        getDepositPositions => deposit_positions
        getBorrowPositions => borrow_positions
        getPoolsMap => pools_map
        getPoolAllowed => pools_allowed
        getPriceAggregatorAddress => price_aggregator_address
        getAssetConfig => asset_config
        lastEModeCategoryId => last_e_mode_category_id
        getEModes => e_mode_category
        getAssetEModes => asset_e_modes
        getEModesAssets => e_mode_assets
        getIsolatedAssetDebtUsd => isolated_asset_debt_usd
        getCollateralAmountForToken => get_collateral_amount_for_token
        getBorrowAmountForToken => get_borrow_amount_for_token
        getAccountHealthFactor => get_account_health_factor
        canBeLiquidated => can_be_liquidated
        getTotalBorrowInDollars => get_total_borrow_in_dollars
        getTotalCollateralAvailable => get_total_collateral_in_dollars
        getLiquidationCollateralAvailable => get_liquidation_collateral_available
        getLtvCollateralInDollars => get_ltv_collateral_in_dollars
    )
}

multiversx_sc_wasm_adapter::async_callback! { lending_pool }
