[package]
name = "price_aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.price_aggregator]
path = ".."

[dependencies.multiversx-sc]
version = "0.54.6"

[dependencies.multiversx-sc-meta-lib]
version = "0.54.6"
