[settings]
main = "main"

[contracts.main]
name = "liquidity_pool"

[[proxy]]
path = "../lending_pool/src/proxy_pool.rs"

[[proxy]]
path = "../lending_pool/tests/proxys/proxy_liquidity_pool.rs"

[[proxy]]
path = "interactor/src/proxy.rs"
 
