[workspace]
members = [
    "liquidity_pool",
    "liquidity_pool/meta",
    "lending_pool",
    "lending_pool/meta",
    "common/structs",
    "common/constants",
    "common/events",
    "price-aggregator",
    "price-aggregator/meta",
    "flash_mock",
    "flash_mock/meta",
]
