[workspace]
members = [
    "liquidity_pool",
    "liquidity_pool/meta",
    "lending_pool",
    "lending_pool/meta",
    "common/structs",
    "common/checks",
    "common/tokens",
    "common/events",
    "price-aggregator",
    "price-aggregator/meta"
]
