[package]
name = "price-aggregator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.price-aggregator]
path = ".."

[dependencies.multiversx-sc]
version = "0.54.0"

[dependencies.multiversx-sc-meta-lib]
version = "0.54.0"
default-features = false
