[package]
name = "aggregator-mock-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.aggregator-mock]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.0"
