// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    price_aggregator
    (
        init => init
        upgrade => upgrade
        submit => submit
        submitBatch => submit_batch
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        submission_count => submission_count
        getPairDecimals => get_pair_decimals
        latestRoundData => latest_round_data
        latestPriceFeed => latest_price_feed
        latestPriceFeedOptional => latest_price_feed_optional
        getOracles => get_oracles
        addOracles => add_oracles
        removeOracles => remove_oracles
        setSubmissionCount => set_submission_count
        setPairDecimals => set_pair_decimals
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
