[package]
name = "controller-meta"
version = "0.0.0"
authors = ["Mihai Eremia <mihai@xoxno.com>"]
edition = "2021"
publish = false

[dependencies.controller]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
