[package]
name = "controller-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dependencies.controller]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.0"
