[settings]
main = "main"

[contracts.main]
name = "price-aggregator"

[[proxy]]
path = "../lending_pool/src/proxy_price_aggregator.rs"

[[proxy]]
path = "../lending_pool/tests/proxys/proxy_aggregator.rs"

[[proxy]]
path = "interactor/src/proxy.rs"
 
