[package]
name = "swap-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.swap-mock]
path = ".."

[dependencies.multiversx-sc]
version = "0.59.0"

[dependencies.multiversx-sc-meta-lib]
version = "0.59.0"
