[package]
name    = "common-errors"
version = "0.0.0"
authors = ["Mihai Eremin <mihai@xoxno.com>"]
edition = "2021"

[lib]
path = "src/errors.rs"

[dependencies.multiversx-sc]
version = "0.56.0"

[dependencies.common-constants]
path = "../constants"