[package]
name    = "common-proxies"
version = "0.0.0"
authors = ["Mihai Eremia <mihai@xoxno.com>"]
edition = "2021"

[lib]
path = "src/mod.rs"
doctest = false

[dependencies.multiversx-sc]
version = "0.59.0"

[dependencies.common-structs]
path = "../structs"
