[package]
name    = "common-math"
version = "0.0.0"
authors = ["Mihai Eremin <mihai@xoxno.com>"]
edition = "2021"

[lib]
path = "src/math.rs"

[dependencies.multiversx-sc]
version = "0.57.0"

[dependencies.common-constants]
path = "../constants"