[package]
name = "flash-mock-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.flash-mock]
path = ".."

[dependencies.multiversx-sc]
version = "0.57.0"

[dependencies.multiversx-sc-meta-lib]
version = "0.57.0"
