// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           25
// Async Callback (empty):               1
// Total number of exported functions:  28

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    liquidity_layer
    (
        init => init
        upgrade => upgrade
        getSuppliedScaled => supplied
        getRevenueScaled => revenue
        getBorrowedScaled => borrowed
        getParams => params
        getBorrowIndex => borrow_index
        getSupplyIndex => supply_index
        getLastTimestamp => last_timestamp
        updateIndexes => update_indexes
        supply => supply
        borrow => borrow
        withdraw => withdraw
        repay => repay
        flashLoan => flash_loan
        createStrategy => create_strategy
        addBadDebt => add_bad_debt
        seizeDustCollateral => seize_dust_collateral
        claimRevenue => claim_revenue
        getCapitalUtilisation => get_capital_utilisation
        getReserves => get_reserves
        getDepositRate => get_deposit_rate
        getBorrowRate => get_borrow_rate
        getDeltaTime => get_delta_time
        getProtocolRevenue => get_protocol_revenue
        getSuppliedAmount => get_supplied_amount
        getBorrowedAmount => get_borrowed_amount
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
