name: CI

on:
  push:
    branches: [ master, feat/*, rc/* ]
  pull_request:
    branches: [ master, feat/*, rc/* ]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v4.2.2
    with:
      rust-toolchain: stable
      coverage-args: --ignore-filename-regex='/\/(tests|.*_mock)\/|\/.cargo\/git\/|\/.rustup\/toolchains\/|\/controller\/tests\/|\/flash_mock\/|\/meta\/src\/|\/.*proxies.*\/|\/.*proxy.*\/|\/[^\/]*proxy[^\/]*$/' --output ./coverage.md
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}